name: Deploy Unstable Manual

on:
  workflow_run:
    workflows:
      - Build
    branches:
      - main
    types:
      - completed
jobs:
  deploy-unstable:
    name: Deploy

    runs-on: ubuntu-latest
    if: github.repository == 'zhaofengli/colmena'

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@c723f3a885e3f1d866d91f4f0c33dd44b1fc7c60 # v18

      - name: Enable Binary Cache
        uses: cachix/cachix-action@v16
        with:
          name: colmena
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      # == Manual
      - name: Build manual
        run: nix build .#manual -L

      - name: Deploy manual
        uses: JamesIves/github-pages-deploy-action@v4.7.3
        with:
          branch: gh-pages
          folder: result
          target-folder: unstable

      # == Redirect Farm
      # /future_api_version -> /unstable
      - name: Check future API version
        run: echo "api_version=$(nix eval .#colmena.apiVersion)" >> $GITHUB_ENV

      - name: Build redirect farm
        run: nix build .#manual.redirectFarm -L

      - name: Deploy redirect farm
        uses: JamesIves/github-pages-deploy-action@v4.7.3
        with:
          branch: gh-pages
          folder: result-redirectFarm
          target-folder: '${{ env.api_version }}'
